import { diffWords } from "diff";
import type { RenderInput, Renderer, RunResult } from "../types/index.js";

export class HtmlRenderer implements Renderer {
  readonly target = "html" as const;

  render(input: RenderInput): string {
    const { prompt, results, generatedAt } = input;
    const totalCost = results.reduce((s, r) => s + r.costUsd, 0);
    const totalLatency = Math.max(0, ...results.map((r) => r.latencyMs));
    const baseline = results.find((r) => !r.error && r.output.length > 0);

    const panelsHtml = results
      .map((r) => renderPanel(r, baseline))
      .join("\n");

    return `<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>promptdiff report</title>
<style>${CSS}</style>
</head>
<body>
<header class="header">
  <div class="header-logo">promptdiff</div>
  <button class="theme-toggle" id="themeToggle" aria-label="Toggle theme">
    <svg class="icon-sun" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>
    <svg class="icon-moon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
  </button>
</header>

<main class="main">
  <section class="prompt-section">
    <div class="section-label">PROMPT</div>
    <pre class="prompt-block">${esc(prompt)}</pre>
    <div class="run-meta">Run &middot; ${esc(generatedAt.toISOString().replace("T", " ").slice(0, 19))} &middot; total ${formatCost(totalCost)} &middot; ${(totalLatency / 1000).toFixed(1)}s</div>
  </section>

  <section class="panels-grid">
    ${panelsHtml}
  </section>
</main>

<footer class="footer">
  Generated by promptdiff &middot; <a href="https://github.com/lucalouren/promptdiff">github.com/lucalouren/promptdiff</a>
</footer>

<script>${JS}</script>
</body>
</html>`;
  }
}

function renderPanel(result: RunResult, baseline: RunResult | undefined): string {
  const { spec, usage, latencyMs, costUsd, error } = result;
  const isError = Boolean(error);
  const isEmpty = !isError && result.output.length === 0;
  const isBaseline = baseline === result;

  let bodyHtml: string;
  if (isError) {
    bodyHtml = `<div class="output-error"><span class="error-pill">ERROR</span>${esc(error!.message)}</div>`;
  } else if (isEmpty) {
    bodyHtml = `<div class="output-empty">(no output — model used all tokens on reasoning)</div>`;
  } else if (isBaseline || !baseline) {
    bodyHtml = `<pre class="output-text">${esc(result.output)}</pre>`;
  } else {
    bodyHtml = `<pre class="output-text">${renderDiff(baseline.output, result.output)}</pre>`;
  }

  return `<div class="panel${isError ? " panel-error" : ""}">
  <div class="panel-header">
    <div class="provider-name${isError ? " provider-error" : ""}">${esc(spec.provider.toUpperCase())}</div>
    <div class="model-name">${esc(spec.model)}</div>
  </div>
  <div class="badges">
    <span class="badge">${usage.inputTokens}in / ${usage.outputTokens}out</span>
    <span class="badge ${latencyClass(latencyMs)}">${(latencyMs / 1000).toFixed(1)}s</span>
    <span class="badge">${formatCost(costUsd)}</span>
  </div>
  <div class="panel-body">
    ${bodyHtml}
  </div>
</div>`;
}

function renderDiff(base: string, target: string): string {
  const changes = diffWords(base, target);
  const parts: string[] = [];
  for (const ch of changes) {
    const text = esc(ch.value);
    if (ch.added) {
      parts.push(`<span class="diff-ins">${text}</span>`);
    } else if (ch.removed) {
      parts.push(`<span class="diff-del">${text}</span>`);
    } else {
      parts.push(text);
    }
  }
  return parts.join("");
}

function latencyClass(ms: number): string {
  if (ms < 2000) return "latency-fast";
  if (ms < 5000) return "latency-mid";
  if (ms < 10000) return "latency-slow";
  return "latency-very-slow";
}

function formatCost(usd: number): string {
  if (usd === 0) return "$0.0000";
  if (usd < 0.0001) return "<$0.0001";
  return `$${usd.toFixed(4)}`;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const CSS = `
:root {
  --bg: #0a0a0a;
  --surface: #141414;
  --surface-elevated: #1c1c1c;
  --border: #262626;
  --text: #ededed;
  --text-secondary: #a3a3a3;
  --text-muted: #737373;
  --accent: #3b82f6;
  --diff-ins-bg: rgba(34, 197, 94, 0.18);
  --diff-ins-text: #86efac;
  --diff-del-bg: rgba(239, 68, 68, 0.18);
  --diff-del-text: #fca5a5;
  --error-text: #fca5a5;
  --latency-fast: #86efac;
  --latency-mid: #fde68a;
  --latency-slow: #fdba74;
  --latency-very-slow: #fca5a5;
}

[data-theme="light"] {
  --bg: #fafafa;
  --surface: #ffffff;
  --surface-elevated: #f4f4f5;
  --border: #e4e4e7;
  --text: #18181b;
  --text-secondary: #52525b;
  --text-muted: #a1a1aa;
  --accent: #2563eb;
  --diff-ins-bg: rgba(34, 197, 94, 0.15);
  --diff-ins-text: #166534;
  --diff-del-bg: rgba(239, 68, 68, 0.15);
  --diff-del-text: #991b1b;
  --error-text: #991b1b;
  --latency-fast: #166534;
  --latency-mid: #854d0e;
  --latency-slow: #c2410c;
  --latency-very-slow: #991b1b;
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: var(--bg);
  color: var(--text);
  font-size: 14px;
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
  transition: color 150ms, background-color 150ms;
}

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 56px;
  padding: 0 24px;
  border-bottom: 1px solid var(--border);
  transition: border-color 150ms;
}

.header-logo {
  font-size: 18px;
  font-weight: 600;
  color: var(--text);
  letter-spacing: -0.01em;
}

.theme-toggle {
  background: none;
  border: none;
  color: var(--text-secondary);
  cursor: pointer;
  padding: 6px;
  border-radius: 6px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: color 150ms;
}
.theme-toggle:hover { color: var(--text); }

[data-theme="dark"] .icon-sun { display: none; }
[data-theme="dark"] .icon-moon { display: block; }
[data-theme="light"] .icon-sun { display: block; }
[data-theme="light"] .icon-moon { display: none; }

.main {
  max-width: 1400px;
  margin: 0 auto;
  padding: 32px 24px;
}

.section-label {
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-muted);
  margin-bottom: 8px;
}

.prompt-block {
  font-family: ui-monospace, "SF Mono", Menlo, "Cascadia Code", Consolas, monospace;
  font-size: 13px;
  line-height: 1.6;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 16px 20px;
  white-space: pre-wrap;
  word-break: break-word;
  color: var(--text);
  transition: background-color 150ms, border-color 150ms;
}

.run-meta {
  font-size: 12px;
  color: var(--text-muted);
  margin-top: 12px;
}

.panels-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 8px;
  margin-top: 32px;
}

.panel {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  display: flex;
  flex-direction: column;
  transition: border-color 150ms, background-color 150ms;
}
.panel:hover { border-color: var(--surface-elevated); }

.panel-header {
  padding: 16px 20px 12px;
  border-bottom: 1px solid var(--border);
}

.provider-name {
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--accent);
}
.provider-error { color: var(--error-text); }

.model-name {
  font-family: ui-monospace, "SF Mono", Menlo, "Cascadia Code", Consolas, monospace;
  font-size: 13px;
  color: var(--text-secondary);
  margin-top: 2px;
}

.badges {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  padding: 12px 20px;
}

.badge {
  font-family: ui-monospace, "SF Mono", Menlo, "Cascadia Code", Consolas, monospace;
  font-size: 11px;
  font-weight: 500;
  color: var(--text-secondary);
  background: var(--surface-elevated);
  padding: 4px 8px;
  border-radius: 4px;
  transition: background-color 150ms;
}

.latency-fast { color: var(--latency-fast); }
.latency-mid { color: var(--latency-mid); }
.latency-slow { color: var(--latency-slow); }
.latency-very-slow { color: var(--latency-very-slow); }

.panel-body {
  padding: 16px 20px 20px;
  flex: 1;
  max-height: 70vh;
  overflow-y: auto;
}

.output-text {
  font-family: ui-monospace, "SF Mono", Menlo, "Cascadia Code", Consolas, monospace;
  font-size: 13px;
  line-height: 1.6;
  white-space: pre-wrap;
  word-break: break-word;
  color: var(--text);
  user-select: text;
  margin: 0;
}

.output-empty {
  font-style: italic;
  color: var(--text-muted);
  font-size: 13px;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 80px;
  text-align: center;
}

.panel-error { border-color: var(--error-text); }

.error-pill {
  display: inline-block;
  font-family: ui-monospace, "SF Mono", Menlo, "Cascadia Code", Consolas, monospace;
  font-size: 10px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--bg);
  background: var(--error-text);
  padding: 2px 6px;
  border-radius: 3px;
  margin-right: 8px;
  vertical-align: middle;
}

.output-error {
  color: var(--error-text);
  font-family: ui-monospace, "SF Mono", Menlo, "Cascadia Code", Consolas, monospace;
  font-size: 13px;
  line-height: 1.6;
  white-space: pre-wrap;
  word-break: break-word;
}

.diff-ins {
  background: var(--diff-ins-bg);
  color: var(--diff-ins-text);
  border-radius: 2px;
  padding: 0 1px;
}

.diff-del {
  background: var(--diff-del-bg);
  color: var(--diff-del-text);
  border-radius: 2px;
  padding: 0 1px;
  text-decoration: line-through;
}

.footer {
  text-align: center;
  padding: 24px;
  font-size: 12px;
  color: var(--text-muted);
  border-top: 1px solid var(--border);
  transition: border-color 150ms;
}
.footer a {
  color: var(--accent);
  text-decoration: none;
}
.footer a:hover { text-decoration: underline; }

@media (max-width: 767px) {
  .header { padding: 0 16px; }
  .main { padding: 20px 16px; }
  .panels-grid { grid-template-columns: 1fr; }
  .panel-body { max-height: none; }
}

@media (min-width: 768px) and (max-width: 1023px) {
  .panels-grid { grid-template-columns: repeat(2, 1fr); }
}
`;

const JS = `
(function() {
  var html = document.documentElement;
  var btn = document.getElementById('themeToggle');
  btn.addEventListener('click', function() {
    var next = html.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    html.setAttribute('data-theme', next);
  });
})();
`;
